version: '3.4'

x-common-variables: &common-variables
  POSTGRES_USER: trunk_player_user
  POSTGRES_PASSWORD: changeme
  POSTGRES_DB: trunk_player
  POSTGRES_HOST: postgres
  POSTGRES_PORT: 5432

services:
  db:
    image: postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      <<: *common-variables
  sdr:
    image: gibby/sdr-trunk:latest
    restart: always
    privileged: true
    volumes:
      - config:/home/radio/trunk-player/config
      - audio_files:/home/radio/trunk-player/audio_files
      - liquidsoap:/home/radio/trunk-player/liquidsoap
      - /dev/bus/usb:/dev/bus/usb
    links:
      - "db:postgres"
    environment:
      <<: *common-variables
      ENCODING_LOGGING_LEVEL: INFO
      START_TRUNK_PLAYER: "true"
      LOCAL_AUDIO_FILES: "true"
      ALLOWED_HOSTS: "['localhost', '127.0.0.1', '[::1]']"
      DJANGO_ADMIN: changeme
      DJANGO_PASS: changeme
      DJANGO_EMAIL: trunk-player@changeme.com
      SECRET_KEY: "changme"
      SITE_TITLE: Trunk-Player
      SITE_EMAIL: trunk-player@changeme.com
      DEFAULT_FROM_EMAIL: Trunk Player <trunk-player@changeme.com>
      AUDIO_URL_BASE: /audio_files/
      TZ: America/New_York
      ALLOW_GOOGLE_SIGNIN: "False"
      DEBUG: "False"
      EMAIL_HOST: email-smtp.us-east-1.amazonaws.com
      EMAIL_PORT: 587
      EMAIL_HOST_USER: changme
      EMAIL_HOST_PASSWORD: changeme
      EMAIL_USE_TLS: "True"
    depends_on:
      - db
    ports:
      - 8000:8000
      - 8080:80
